version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: artly-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: artly
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    networks:
      - my-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  neo4j:
    image: neo4j:latest
    container_name: artly-neo4j
    ports:
      - "7687:7687"
      - "7474:7474"
    environment:
      NEO4J_AUTH: neo4j/secret@1234
    networks:
      - my-network
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    healthcheck:
      test: wget http://localhost:7474 || exit 1
      interval: 20s
      timeout: 20s
      retries: 10
      start_period: 60s

  jwtspringbootapp:
    image: jwtspringbootapp:latest
    container_name: jwtspringbootapp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7040:7040"
    environment:
      SPRING_DATA_MONGODB_HOST: mongo
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_DATA_MONGODB_DATABASE: artly
      SPRING_DATA_MONGODB_USERNAME: admin
      SPRING_DATA_MONGODB_PASSWORD: admin123

      SPRING_NEO4J_URI: bolt://neo4j:7687
      SPRING_NEO4J_USERNAME: neo4j
      SPRING_NEO4J_PASSWORD: secret@1234
    depends_on:
      mongo:
        condition: service_healthy
      neo4j:
        condition: service_healthy
    networks:
      - my-network

volumes:
  neo4j_data:
  neo4j_logs:

networks:
  my-network:
    driver: bridge


