spring:
  application:
    name: JWTSecurity

  app:
    jwtSecret: mySecretKey123912738aopsgjnspkmndfsopkvajoirjg94gf2opfng2moknm
    jwtExpirationMs: 3000000

  data:
    mongodb:
      authentication-database: admin
      database: artly
      uri: mongodb+srv://utkarshxf:utkarsh123@cluster0.cv4vjxo.mongodb.net/?retryWrites=true&w=majority

    neo4j:
      uri: neo4j+s://eeb6bc24.databases.neo4j.io
      authentication:
        username: neo4j
        password: cfe0IG8pV2fvQHP3cZ1IDBU_kwBKDNNzNgxNGOad8b0

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  servlet:
    multipart:
      max-file-size: 256MB
      max-request-size: 256MB
      enabled: true

server:
  port: 7040
