name: Deploy to Production

on:
  push:
    branches:
      - main  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/your-app-name:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/your-app-name:latest
          cache-to: type=inline

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            # Pull the latest image
            docker pull ${{ secrets.DOCKER_USERNAME }}/your-app-name:latest
            
            # Stop and remove the old container if it exists
            docker stop app-container || true
            docker rm app-container || true
            
            # Run the new container
            docker run -d \
              --name app-container \
              -p 7040:7040 \
              --restart unless-stopped \
              ${{ secrets.DOCKER_USERNAME }}/your-app-name:latest
